//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoYouth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.Yorum = new HashSet<Yorum>();
            this.YorumsT = new HashSet<YorumsT>();
        }
    
        public int id { get; set; }
        public string Baslik { get; set; }
        public string İcerik { get; set; }
        public string ResimURL { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual KategoriT KategoriT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YorumsT> YorumsT { get; set; }
    }
}
