//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoYouth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int YrmID { get; set; }
        public string AdSoyad { get; set; }
        public string EPosta { get; set; }
        public string İcerik { get; set; }
        public Nullable<bool> onay { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
